replace add-path with GITHUB_ENV
racket/racket pull request #3447
Opened 2020-10-19 15:09 UTC by xxyzz

close #3446

2020-10-19 17:23 UTC, pmatos commented
@xxyzz thanks for the fix. `ci-ubsan` has another occurrence of `add-path`, can you please fix?
Also the reason I didn't use `GITHUB_WORKSPACE` it's because it was broken in github runner. It might have been fixed already. If possible, please fix the other `add_path`. This will trigger a CI run and allows us to check if github has fixed the `GITHUB_WORKSPACE` references inside the docker container.

2020-10-19 18:03 UTC, pmatos requested changes

2020-10-19 18:03 UTC, pmatos commented on .github/workflows/ci-ubsan.yml
> -        echo "::add-path::/__w/racket/racket/racket/bin"
Check line 115 as well pls.

2020-10-19 23:39 UTC, xxyzz commented
It works fine on my forked repo so I guess the bug was fixed.

2020-10-20 06:02 UTC, pmatos commented
> It works fine on my forked repo so I guess the bug was fixed.

It seems the bug is fixed indeed. For the record this was the problem: https://github.community/t/runner-temp-being-emptied-between-jobs/18217/2?u=pmatos

I will merge. Thanks.

2020-10-20 06:02 UTC, merged