ci: cross-compile to iOS for PR
racket/racket pull request #3629
Opened 2021-01-17 17:44 UTC by Bogdanp

This ensures that cross-compilation to iOS for Racket CS works on PR. To test that things work at runtime, we could set up a free account at one of the iOS CI services and have it run daily builds. I'll look into that next weekend.

The PR workflows seemed like a convenient place to put this, but I'm happy to move it elsewhere if there's a better place (cc @pmatos).

Also includes a change to delete some code I accidentally left in on my last PR.

2021-01-18 09:58 UTC, pmatos requested changes
I don't have a way to test it, but overall looks good to me.
Also - should this also be part of the push setup, instead of just PR?

2021-01-18 09:58 UTC, pmatos commented on racket/src/ChezScheme/c/alloc.c
> -#if defined(WRITE_XOR_EXECUTE_CODE)
Shouldn't this be part of another PR? I would like to isolate CI patches, instead of having them together with changes that potentially break code.

2021-01-18 09:58 UTC, pmatos commented on .github/workflows/ci-pr.yml
> +          --enable-racket=${{ github.workspace}}/host-racket/bin/racket \
space after `github.workspace` for consistency.

2021-01-18 09:58 UTC, pmatos commented on .github/workflows/ci-pr.yml
> +          --enable-scheme=${{ github.workspace}}/host-racket/src/build/cs/c
same - space after `github.workspace` for consistency.

2021-01-18 10:17 UTC, Bogdanp commented
Thanks for the review! I've fixed the spacing and added a job for push as well. I'll test it on my fork (I don't think there's a way to test it here w/o merging, is there?) and then circle back here when it passes.

2021-01-18 13:14 UTC, Bogdanp commented
The `push` workflow [passes](https://github.com/Bogdanp/racket/runs/1721529887?check_suite_focus=true) so I've squashed the commits.

2021-01-19 08:05 UTC, pmatos approved these changes
lgtm

2021-01-19 12:08 UTC, merged