API changes supporting better hygiene behavior for first-class definition contexts
racket/racket pull request #3927
Opened 2021-07-22 04:50 UTC by michaelballantyne

This PR implements my proposal from https://github.com/racket/racket/issues/3251. The description below updates the text of that issue. It is written for macro system experts; I plan to write separate documentation for macro authors.

I haven't finished the documentation so the PR is a draft, but the implementation is ready and I'd appreciate comments!

## Summary

The goal of this PR is to make the hygiene behavior of expansion using first-class definition contexts fully in line with the expansion of Racket's core forms, to ensure correct hygiene for forms such as `class` and for DSL expanders. 

The current hygiene behavior supported by definition contexts falls short with respect to three elements: outside-edge scopes, use-site scopes, and the frame-id optimization to avoid unnecessary use-site scopes,

The changes, in summary:

* Each first-class definiton now comes with an associated outside-edge scope.
* The expander tracks sets of use-site scopes to remove with each first-class definition context, rather that in the surrounding expand context.
* `internal-definition-context-introduce` is replaced with operations that manipulate outside-edge and use-site scopes along with inside-edge scopes.
* The expander provides a new primitive operation for applying macro transformers in DSL expanders, replacing `local-apply-transformer`. The operation needs to be primitive in order to cooperate with the new use-site scope behavior. It also allows the DSL expander to specify the binding that the transformer is associated with in order to apply the frame-id optimization and to set the `current-module-code-inspector` appropriately.
* When the context is of type `'expression`, new definition contexts use a new frame-id rather than reuse that from the context.

I also propose to document support for lists of definition contexts in some API arguments as "for backwards compatibility only"; see the "Arguments supporting lists of definition contexts" section.

## Problems and solutions, in detail

### Outside-edge scopes

See <https://github.com/racket/racket/issues/3198> for a description of the problem.

#### Solution

This PR associates an outside-edge scope with each first-class definition context, in addition to the present inside-edge scope.

Both scopes are registered with the expand context for removal at `quote-syntax` and addition via `syntax-local-get-shadower`.

The "API additions and changes" section discusses the operations used to manipulate these scopes.

### Use-site scopes

The existing approach to use-site scopes relies on tracking a set of use-site scopes in the expander context. In the `syntax-local-identifier-as-binding` operation or when a `define` form is expanded, those use-site scopes on the binding identifier that are also in the set tracked by the context are removed from the binder. The set is changed when entering a new expansion context: entering 

This approach leads to two problems.

#### Improper removal of use-site scopes that belong to the surrounding context

Consider this example:

```
#lang racket
(define x 'good)
(let ()
  (define-syntax-rule (m1 arg)
    (local [(define arg 'bad)]
      x))
  (define res (m1 x))
  res) ; => evaluates to 'bad
```

The correct expansion would have the `x` reference refer to the outer binding, not the use-site binder, as it would if the `local` expression were instead a `let`.

Right now, the expansion of `(m1 x)` applies a use-site scope. This scope is recorded in the expand context's set of use-site scopes. Because expansion does not newly enter an expression context before creating the binding for the `define` inside `local`, the use-site scope remains in the set and is removed from the binder. This results in the improper capture of the reference

#### Failure to record use-site scopes when they are disabled in the surrounding context

As noted in https://github.com/racket/racket/pull/2237, the expander currently disables the application of use-site scopes in expression contexts entered via `local-expand`. This PR does not change that behavior, but removes one of its secondary consequences.

Consider the interaction between Turnstile or a DSL expander that expands subexpressions fully with `local-expand`, here simulated by `expr`, with a definition context macro such as `local`:

```
#lang racket
(define-syntax (expr stx)
  (syntax-case stx ()
    [(_ e) (local-expand #'e 'expression '())]))
(expr
 (local [(define-syntax-rule (my-define x v) (define x v))
         (my-define x 5)]
   x))
; x: unbound identifier    
```

`local-expand` given `'expression` sets the expand context value for the use-site set to `#f`, disabling both application and tracking of use-site scopes. When `local` uses `local-expand` to expand the definitions, `local-expand` replaces that `#f` with a new set and records the use-site scope applied to the define. However, that new set only lasts as long as the `local-expand`---in the surrounding context where `local` will use `syntax-local-bind-syntaxes`, the value returns to `#f`. This means that the use-site scope is not removed, and the reference is unbound.

#### Solution

The solution to both of these problems is to track use-site scopes created by expansion for each first-class definition context. Expansion using a first-class definiton context sets the expand context use-site scope set to that stored with the definition context. In the first problem above this ensures that only use-site scopes created during the expansion within `local` are removed from the bindings. In the second, it ensures that the scopes are recorded with the definition context rather than only in the nested expand context that is discarded after the definition expansions.

### Frame-ids

The frame-id optimization ensures that use-site scopes are only applied for expansions where they are potentially necessary. Unless a macro definition and a use site are in the same definition context, the use-site should usually have additional scopes that would prevent use-site binders from capturing definition-site references. Generally the expander associates a frame-id with each definition context, and only applies use-site scopes when the frame-id of the macro binding and use match.

Splicing forms complicate this picture, because spliced macro definitions are bound in the surrounding definition context but their right-hand-sides have the scopes of the inner context. Thus there are no scopes to distinguish use-site binders from introduced references in this case. To accommodate this case, first-class definition contexts conservatively always use the same frame-id as their parent first-class definition context (if any) or the surrounding expansion context.

In a DSL expander, the result of this strategy is that the entire expansion uses a single frame-id and the optimization never applies.

#### Solution

This PR enables the frame-id optimization for some DSL expanders via two changes.

First, when the surrounding expand context is an expression context, syntax-local-make-definition-context creates new frame-id rather than reuses that of the context. This is safe because definitions cannot splice out of an expression context.

Second, the new `syntax-local-apply-transformer` discussed in the "API additions and changes" section accepts a `binding-id` argument indicating the binding associated with a macro transformer. The frame-id associated with this binding is used to apply the frame-id optimization when safe.

Note that this approach is not enough to allow a DSL expander for a language with nested scopes not separated by an expression contexts (a statement-oriented language, for example) to take advantage of the frame-id optimization. That would require an additional mechanism with which the expander could promise that no definitions will splice out from a given context, making it safe to use a new frame-id.

## API additions and changes

The PR adds three new operations: `internal-definition-context- [...]

2021-07-22 04:58 UTC, michaelballantyne commented
(@mflatt, @rmculpepper, and @lexi-lambda might have opinions)

2021-07-22 13:43 UTC, mflatt commented
This looks really great! As far as I can tell, it will be ready to merge as soon as the documentation is updated.

2021-07-22 13:51 UTC, mflatt commented
Really minor, and you should feel free to ignore: I'd prefer that the changes in "src/expander" never have a newline after `require`, use DrRacket-style indentation for `if`, and use two `;` for comments on their own line (more friendly to Emacs modes). This is well below the level of textual-style detail that I'd normally comment on, especially for the rest of the code base, but I've tried to keep "src/expander" especially consistent.

2021-07-23 01:51 UTC, lexi-lambda commented
I have not taken the time to look through absolutely all of this in as much detail as it probably deserves, but overall, this looks great to me. Here are my immediate thoughts from a quick overview:

## Changes to `syntax-local-identifier-as-binding`

> ```racket
> (syntax-local-identifier-as-binding id-stx [intdef-ctx]) → identifier?
> ```
>
> The new optional `intdef-ctx` argument determines which use-site scopes are removed.

As far as I can tell, this operation does not actually need `(syntax-transforming?)` to be `#t` if a first-class definition context is provided, so lumping it into an existing `syntax-local-*` function seems philosophically wrong to me. I’d propose this functionality be exposed through a new function, instead, `internal-definition-context-identifier-as-binding`. (Now there’s a Racket function name if I’ve ever seen one!)

## Lists of first-class definition contexts

> With the current hygiene model and API, it appears that support for lists of definition contexts in these arguments is not necessary. I propose to document as "for backwards compatibility only"

Without other changes, I think this is too aggressive. Suppose I have a macro with a grammar like this:

```racket
(complicated ([foo-id foo-expr] ...)
             ([bar-id bar-expr] ...)
  #:foo special-foo-expr
  #:bar special-bar-expr
  body ...+)
```

And suppose I want `complicated` to have a rather unusual binding structure:

  * The `foo-id`s should be bound in `special-foo-expr`.

  * The `bar-id`s should be bound in `special-bar-expr`.

  * Both the `food-id`s *and* the `bar-id`s should be bound in the `body`s.

This binding structure is strange because it cannot be linearized: neither the `foo-id`s nor the `bar-id`s are bound in a scope that is “inside” the other one, yet both scopes are present around the `body` forms. With a list of definition contexts, this is easy to express: you just provide both definition contexts when expanding the `body`s. But without that capability, it’s not immediately obvious what to do.

One could argue that this structure is strange enough that the Racket macro system does not need to support it. After all, one could (arbitrarily) make the `foo-id` context a parent of the `bar-id` one, then simply avoid applying the `foo-id` context’s *scope* when expanding `special-bar-expr`. This would cause the `foo-id`s to be in context during the expansion of `special-bar-expr`, but otherwise inaccessible without identifier-smuggling shenanigans.

However, this idea that definition contexts should always be linearizable is not one that appears anywhere in the existing documentation, and it is somewhat unintuitive given the fact that *scopes* are quite explicitly unordered and are designed to be able to handle exactly this sort of strange binding structure. Furthermore, I think arranging for all created definition contexts to be (artificially) linearized could be genuinely inconvenient in the construction of particularly complex macros: consider, for example, a macro that has subforms that belong to two different binding spaces (to use Matthew’s recently introduced terminology). The macro’s helper functions might process these subforms independently, creating two definition contexts that have no particular relationship to one another, but nonetheless must both be brought into scope in case a subform has any cross-binding space references.

I think these examples highlight how there are really two meaningfully distinct interpretations given to `local-expand`’s `intdef-ctxs` argument:

  1. The bindings in the given `intdef-ctx` are in scope during the expansion of this subform, so they must be added to the expansion context’s binding table.

  2. The subform being expanded *belongs* to the given `intdef-ctx`.

An example where the former is true but not the latter is when expanding the body of a form like `local`: local definitions’ bindings must be visible within the body, but the body forms do not actually belong to that definition context.

### Proposal: Decouple binding table extension from transformer application

Given all of the above, I propose a change that may be seen as somewhat radical: I think we should add a new primitive for extending the expansion context’s binding table without requiring a fresh transformer application.

This new primitive might have an API like this:

```racket
(syntax-local-call-with-bindings intdef-ctxs proc) -> any
  intdef-ctxs : (or/c internal-definition-context?
                      (listof internal-definition-context?))
  proc : (-> any)
```

This applies `proc` in a context that is identical to the current one, except that the binding mixins from the provided definition contexts are folded into the current expansion context. Giving the user the option to do this directly has a lot of advantages:

  * Functions like `local-expand` don’t need to worry about handling point 1 from above, only point 2, so they can accept a single definition context instead of a list.

  * Functions like `syntax-local-value` no longer need to worry about internal definition contexts at all.

    (Currently, there are actually a number of functions littered throughout Racket that don’t take an `intdef-ctxs` argument but really ought to, such as the `static` syntax class from `syntax/parse`. Threading definition contexts through all these functions is a huge pain, and `syntax-local-value` ultimately just adds the given contexts’ bindings to the current expansion context, anyway.)

  * Macro authors don’t have to take nearly as much care to pass definition contexts to all the functions in the `syntax-local` zoo that need them. Rather, while running phase 1 code that is morally “inside” the definition context, they can simply parameterize the binding environment appropriately.

This is something of a departure from the design of existing macro system APIs, since historically, the expander has offered no way to modify the expansion context except by trampolining through another macro invocation. However, I think the things we’ve been doing lately really encourage moving in this direction, and I think this is in line with a broader vision of someday having a more modular expander.

Indeed, I would advocate for the addition of further functions that expose other aspects of the expansion context in more direct ways. For example, I’d be interested in a `syntax-local-call-with-introduction-scope` that directly sets the macro-introduction scope used by `syntax-local-introduce` to an arbitrary value, or a `syntax-local-call/capture-lifts` function that captures uses of `syntax-local-lift-expression` that occur while evaluating an arbitrary thunk. Of course, these things don’t have to happen now, they’re just examples of things we could do in the future.

## The `add-scope?` option

> Some previous uses of definition contexts, such as an earlier implementation of `splicing-syntax-parameterize`, used definition contexts to extend the expander environment but did not intend to create a new scope. The `add-scope?` argument to `syntax-local-make-definition-context` supported this situation.
>
> […]
>
> I propose we document the `add-scope?` argument as for backwards compatibility only.

Personally, I set `add-scope?` to `#f` all the time, but not because I want to avoid a new scope being created at all. Rather, I use `internal-definition-context-introduce` to add the scope explicitly, since don’t always want the scope to be automatically added by `local-expand`. The reason is the same one I mentioned in the previous section: I need the bindings to be brought into scope, but the expression to be expanded doesn’t actually belong to the definition context.

Fortunately, my proposed `syntax-local-call-with-bindings` primitive supports this use case much more neatly than the `add-scope?` argument does. In situations where I don’t want the scope to be automatically added, I just wouldn’t pass the definition context to `local-expand` in the fi [...]

2021-07-26 02:38 UTC, michaelballantyne commented
Thanks for the comments @lexi-lambda!

> lumping it into an existing syntax-local-* function seems philosophically wrong to me

I can see where you're coming from here. I think it would make the API slightly harder to use, though, with two names rather than one to remember for similar situations. I also can't think of situations where it would be important to use outside of `syntax-transforming?` contexts. By the time expansion is over the fate of use-site scopes should be resolved. Do you have a situation in mind?

> And suppose I want complicated to have a rather unusual binding structure...

I indeed hadn't thought about non-linearizable / DAG-shaped scoping structure, thanks!
Unless I missed something, the solutions you propose don't address the original problem I ran into with lists of definition contexts: my new approach to use-site scopes needs local-expand to record use-site scopes in a single definition context representing the current (conceptual) scope. Given a list, there isn't a good way to choose which.

I think the right way to support DAG-structured scope with my proposal is to allow a first-class definition context to have multiple parent contexts, by widening the domain of the `parent-ctx` argument to `syntax-local-make-definition-context` to accept a list of contexts. That way there is a single current definition context to which the `local-expand`ed syntax "belongs", but bindings from the parent contexts can be available in the expander environment.

Part of my goal with this design is to make first-class definition contexts map one-to-one with our intuitive or conceptual notion of lexical "scopes". Binding as sets of scopes implements each such conceptual scope with a combination of elements: outside-edge and inside-edge scopes, an environment frame, a frame id, and a set tracking use-site scopes created during expansion within the conceptual scope. With this PR definition contexts bundle all those elements together, and macro authors can use definition contexts and their parent relationships to construct their intended scoping structure. So I'm explicitly trying to come up with a model that avoids your interpretation #1 of the `intdef-ctx` argument. Similarly, the `#:add-scope?` argument only makes sense to me given a lower-level interpretation of definition contexts as primarily representing environment frames.

I'd like to move on from this PR (I've been at it for a long time now), so I'm inclined to merge it without support for DAG-shaped scope for the time being unless there are existing macros that depend on it. Support for multiple parent contexts can be added later. Would that break anything for you?

2021-07-26 10:15 UTC, lexi-lambda commented
> I can see where you're coming from here. I think it would make the API slightly harder to use, though, with two names rather than one to remember for similar situations. I also can't think of situations where it would be important to use outside of `syntax-transforming?` contexts. By the time expansion is over the fate of use-site scopes should be resolved. Do you have a situation in mind?

I don’t have a particular use case in mind, but it isn’t clear to me whether or not `syntax-local-identifier-as-binding` has a legitimate purpose *without* providing a definition context argument. Therefore, if the single-argument use is effectively deprecated, it seems conceptually cleaner to just introduce a separate function. However, if it isn’t deprecated, and it has some legitimate use I’m not aware of, I’m much more partial to your counterargument.

> I indeed hadn't thought about non-linearizable / DAG-shaped scoping structure, thanks!

I think my focus on non-linearizable contexts in my previous comment may have a mistake—to be honest, while they are interesting, they’re really only a small portion of the problem I’m alluding to.

Consider `local`. Its grammar is this:

```racket
(local [local-defn ...] body ...+)
```

We want to implement `local` using a first-class definition context for the `local-defn`s, but *not* for the `body` forms, which we can just wrap in an empty `let` and expand as an expression. Clearly, the `local-defn`s *belong* to the definition context, so when we call `local-expand`, we need to pass the definition context as an argument in order to (among other things) accumulate use-site scopes. But when we expand `(let () body ...)`, we aren’t in the definition context anymore, but we still need those bindings to be in scope.

Perhaps this isn’t especially compelling to you because the outer `let` around the `body` forms will inevitably cause the expander  to switch into a separate context, anyway. Fair enough—but then let’s consider a weirder variant, `weird-local`. `weird-local` is just like `local`, but while the `local-defn`s are *in context* in the `body` forms, they aren’t automatically *in scope*. That is, the definition context’s scopes are *not* added to the `body` forms, but identifier-smuggling macros might still reference the created bindings. There is no way to express this sort of thing right now without setting the `add-scope?` argument to `#f` and manually managing introduction of the scope.

Perhaps this still isn’t compelling to you, because you thing `weird-local` is simply too weird to be worth supporting. Again, fair enough—but `weird-local` is ultimately a simplified representative of more complicated yet still quite useful applications of first-class definition contexts.

> Part of my goal with this design is to make first-class definition contexts map one-to-one with our intuitive or conceptual notion of lexical "scopes". Binding as sets of scopes implements each such conceptual scope with a combination of elements: outside-edge and inside-edge scopes, an environment frame, a frame id, and a set tracking use-site scopes created during expansion within the conceptual scope. With this PR definition contexts bundle all those elements together, and macro authors can use definition contexts and their parent relationships to construct their intended scoping structure. So I'm explicitly trying to come up with a model that avoids your interpretation #1 of the `intdef-ctx` argument. Similarly, the `#:add-scope?` argument only makes sense to me given a lower-level interpretation of definition contexts as primarily representing environment frames.

I think the heart of my quibbles is that I disagree with this conclusion. As demonstrated above, even if you treat a first-class definition context as a first-class definition context, there are still situations where you want to bring those bindings into context to expand a subexpression (not necessarily a sub-definition context, so you can’t rely on the `parent-ctx` chain!) that does not belong to the definition context.

`local` is a canonical example of a macro that codifies this idea that a form does not have to be inside a definition context to see its bindings, and in fact a definition context *can* be intuitively viewed as a “collection of bindings” in a similar sense to binding pairs in a `let` form are, and I think that perspective is one that is important to continue to support without necessarily having to trampoline into a sub-expansion context within the definition context using `#%expression` or something like that.

> Unless I missed something, the solutions you propose don't address the original problem I ran into with lists of definition contexts: my new approach to use-site scopes needs local-expand to record use-site scopes in a single definition context representing the current (conceptual) scope. Given a list, there isn't a good way to choose which.

I don’t think this is a problem with anything I presented in my previous comment, because there is still always exactly one definition context that any given form belongs to, which is the one that should be passed to `local-expand`. Other definition contexts’ bindings merely need to be brought into context during the expansion.

> I think the right way to support DAG-structured scope with my proposal is to allow a first-class definition context to have multiple parent contexts, by widening the domain of the `parent-ctx` argument to `syntax-local-make-definition-context` to accept a list of contexts. That way there is a single current definition context to which the `local-expand`ed syntax "belongs", but bindings from the parent contexts can be available in the expander environment.

I wouldn’t be opposed to this idea in general, but I still really think the `parent-ctx` argument makes sense as a convenience feature. I don’t think definition contexts should need to have any hierarchical structure. Scopes don’t, and I don’t think there’s any way to justify definition contexts needing it independently. As far as I can tell, nothing in your design depends on it, and imposing this requirement on macro authors seems to mostly just make things more complicated—relative to giving them a primitive to bring the bindings into scope explicitly—for no gain.

> I'd like to move on from this PR (I've been at it for a long time now), so I'm inclined to merge it without support for DAG-shaped scope for the time being unless there are existing macros that depend on it. Support for multiple parent contexts can be added later. Would that break anything for you?

Would it actually break any programs I’ve written? Probably not. I suspect all my programs would continue to do the same thing because the differences in behavior are not significant enough to actually cause issues in practice. However, it very much *would* cause programs of mine to be “philosophically incorrect,” in that they use features like passing lists of definition contexts to `local-expand` and setting `add-scope?` to `#f` with no migration path to a non-deprecated API.

2021-07-27 04:52 UTC, michaelballantyne commented
@lexi-lambda 

> However, if it isn’t deprecated, and it has some legitimate use I’m not aware of, I’m much more partial to your counterargument.

I think there remain legitimate uses without a definition context argument. For example, an abstraction over `define` might want to construct an identifier that will match the final definition binding for use as a key in a free- or bound-identifier table.

> I don’t think this is a problem with anything I presented in my previous comment, because there is still always exactly one definition context that any given form belongs to, which is the one that should be passed to local-expand. Other definition contexts’ bindings merely need to be brought into context during the expansion.

Sorry, I had misread something previously. Now it makes sense.

However,

> `weird-local` is just like `local`, but while the `local-defns` are in context in the body forms, they aren’t automatically in scope... There is no way to express this sort of thing right now without setting the `add-scope?` argument to `#f` and manually managing introduction of the scope.

I think I understand where we were failing to connect now. The above suggests you use the definition context scope as an outside-edge scope: one that should be applied to bindings and references in a context before macro expansion moves anything, but not to syntax that is moved by expansion into the definition context. The default `add-scope?` `#t` behavior corresponds instead to an inside-edge scope: one that should be added to any identifier that ends up in the definition context, whether there originally or by expansion. And a separate outside-edge scope was missing.

With the PR definition contexts now come with both outside- and inside-edge scopes. To get the behaviors you're looking for, a macro should manipulate the outside-edge scope with `internal-definiton-context-add-scopes` rather than the inside-edge with `internal-definition-context-introduce`. `weird-local` should add the outside-edge scope only to the `local-defns` and not the body forms. The inside-edge scope for the definition context isn't needed on the body forms in this (weird) form, but it does no harm because the absence of the outside-edge scope ensures the `local-defns` bindings are out of scope.

2021-07-27 22:45 UTC, lexi-lambda requested changes
> I think there remain legitimate uses without a definition context argument. For example, an abstraction over `define` might want to construct an identifier that will match the final definition binding for use as a key in a free- or bound-identifier table.

Alright, that’s fair—I don’t feel as strongly about this point, then.

I do still think that splitting this functionality out into a separate function would be more consistent with the design of the rest of the syntax API. For example, we have `syntax-local-introduce` and `internal-definition-context-introduce`, not an optional `intdef-ctx` argument to `syntax-local-introduce`. When an optional `intdef-ctx` argument *is* present, it usually augments the functionality that the function already performs, not replace it completely.

In your design, it sounds like `syntax-local-identifier-as-binding` does a fundamentally different thing when given an `intdef-ctx` argument; that is, it no longer removes the use-site scopes that it would have without the argument. I think that’s confusing and inconsistent, so I would still prefer the separate function, but it isn’t a strong enough preference that I will die on this hill.

> I think I understand where we were failing to connect now. The above suggests you use the definition context scope as an outside-edge scope: one that should be applied to bindings and references in a context before macro expansion moves anything, but not to syntax that is moved by expansion into the definition context. The default `add-scope?` `#t` behavior corresponds instead to an inside-edge scope: one that should be added to any identifier that ends up in the definition context, whether there originally or by expansion. And a separate outside-edge scope was missing.
> 
> With the PR definition contexts now come with both outside- and inside-edge scopes. To get the behaviors you're looking for, a macro should manipulate the outside-edge scope with `internal-definiton-context-add-scopes` rather than the inside-edge with `internal-definition-context-introduce`. `weird-local` should add the outside-edge scope only to the `local-defns` and not the body forms. The inside-edge scope for the definition context isn't needed on the body forms in this (weird) form, but it does no harm because the absence of the outside-edge scope ensures the `local-defns` bindings are out of scope.

Yes, I think I better understand the disconnect now. Unfortunately, the remaining confusion appears to stem from the fact that—as far as I can tell—your description does not actually line up with the implementation.

Before your PR, the `add-scope?` option controlled whether or not the definition context’s scope was added to the syntax object provided to `local-expand` both before **and** after its expansion. See this line: https://github.com/racket/racket/blob/f1e6ac414707270edd4a6647008a4a903fe7d12e/racket/src/expander/expand/local-expand.rkt#L118

This means the existing behavior essentially treats the definition context’s scope as both an inside- and outside-edge scope.

With your PR, definition contexts now have separate inside- and outside-edge scopes. On paper, that’s a great idea—but the aforementioned line in `do-local-expand` is still present, which means `add-scope?` will now cause what is supposed to be the inside-edge scope to be added to everything expanded in the context *before* it’s expanded, which is obviously wrong!

So at the very least, something doesn’t quite line up between your description of what you think the mental model *should* be and what the implementation actually does. But I don’t know how to fix it: changing the meaning of the `add-scope?` option to do what you describe sounds extremely backwards-incompatible to me. Regardless, I think this PR as-written isn’t quite right.

2021-07-28 01:57 UTC, lexi-lambda reviewed
Alright, Michael and I had a long phone call about this hashing the details out, and he successfully convinced me of both the correctness and backwards-compatibility of this design. Here are the main subtleties discussed:

  * It’s perfectly backwards-compatible to think of the scope historically associated with first-class definition contexts as being exclusively the inside-edge scope. The fact that `local-expand` only adds the inside-edge scope is fine, as that is consistent with the historical (mis)behavior.

  * Historically, the default `#t` value for `add-scope?` has allowed macro authors to rely on `local-expand` to introduce syntax into the definition context. However, going forward, correct use of first-class definition contexts will always require explicit use of `internal-definition-context-add-scopes` to add the outside-edge scope.

  * Given the above point, setting `add-scope?` to `#f` is unnecessary, since the effect I mentioned using it for in previous comments is accomplished by simply omitting the outside-edge scope. The addition of the inside-edge scope in such situations is harmless, since the bindings’ accessibility is determined by other scopes.

  * The fact that parent definition contexts don’t have their inside-edge scope automatically added during expansion is fine, since the “late” addition of the inside-edge scope is only necessary to reference bindings introduced in the current definition context. (Adding parents’ inside-edge scopes would be harmless, but omitting them is a valid optimization.)

  * My proposed `syntax-local-call-with-bindings` operation goes in roughly the right direction, but it probably isn’t quite right, because it doesn’t adjust the way the expansion context tracks use-site scopes, nor does it add the inside-edge scope for forms expanded immediately within the context. However, a more complete version of this operation can already be effectively implemented using `syntax-local-apply-transformer` (since the addition of the inside-edge scope is now harmless).

Having discussed all those details, my fears in my previous comment are assuaged, so I’m mostly satisfied with the changes in this PR as-written. Here are my (comparatively minor) lingering quibbles:

  1. We both agreed that the domain of `internal-definition-context-remove-scopes` ought to be restricted to an identifier for the same reasons `syntax-local-identifier-as-binding` is. We also agreed that it makes more sense to give it a more purpose-oriented name, like `internal-definition-context-identifier-for-splice`, since it’s really only intended to be used to implement splicing forms.

  2. I personally wish `internal-definition-context-add-scopes` also had a more purpose-oriented name that captured the fact that it is intended to be applied to *the original forms* that make up the definition context, not applied to the results of macroexpansion in the context. (That is, its primary intent is to add the outside-edge scope.) This would make its relationship to `internal-definition-context-introduce` much less confusing.

  3. I still have a preference for a separate `internal-definition-context-identifier-as-binding` operation for somewhat philosophical reasons (and I think it could pair nicely with `internal-definition-context-identifier-for-splice`), but I don’t feel especially strongly about this.

---

@michaelballantyne, one thought I had while typing this up is that it could make sense to replace `internal-definition-context-add-scopes` with an operation that is like `internal-definition-context-introduce`, but exclusively for the outside- rather than the inside-edge scope. I think that would satisfy both our goals:

  * It is more consistent with the rest of the API and gives programmers complete control, if they really want it.

  * Macro authors still only need to call that one function, since the inside-edge scope will get added by `local-expand` anyway.

In an ideal world, I think we would want to call such an operation `internal-definition-context-introduce`, but we can’t reuse that name without breaking backwards-compaitibility. So perhaps we could use a name like `internal-definition-context-original-introduce`, which captures the idea that it should be applied to syntax that originates from the definition context.

2021-07-28 03:21 UTC, michaelballantyne commented
> It could make sense to replace `internal-definition-context-add-scopes` with an operation that is like `internal-definition-context-introduce`, but exclusively for the outside- rather than the inside-edge scope... Macro authors still only need to call that one function, since the inside-edge scope will get added by `local-expand` anyway.

`local-expand` only adds the `inside-edge` scope of the current definition context. Given a chain of definition contexts, only `internal-definition-context-add-scopes` ensures that the inside-edges from the outer contexts are added.

2021-07-28 04:34 UTC, michaelballantyne commented
@lexi-lambda, @mflatt any feelings on:

* `internal-definition-context-splice-binding-identifier` rather than `internal-definition-context-remove-scopes`
* `internal-definition-context-add-initial-scopes` rather than `internal-definition-context-add-scopes`

?

2021-07-30 21:11 UTC, lexi-lambda commented
> `internal-definition-context-splice-binding-identifier` rather than `internal-definition-context-remove-scopes`

I don’t like this name because I think it sounds like it should splice an identifier into the given context, but it’s actually used to build an identifier that can splice into a surrounding context. So I’d prefer a name like `internal-definition-context-identifier-for-splice`.

If you don’t like that name because it sounds like it should access an identifier in the context rather than be an operation on an identifier, you could try something like `internal-definition-context-prune-for-splice`, but I still prefer the former suggestion. This is really just bikeshedding, though.

Of perhaps some interest is the (deprecated) `identifier-remove-from-definition-context` function, which uses an alternate naming scheme that starts with `identifier` rather than `internal-definition-context`. In theory, I think you could even justify commandeering `identifier-remove-from-definition-context` to also remove use-site and the outside-edge scopes (which would undeprecate it), since removing the context’s use-site scopes on such an identifier is harmless and would not cause backwards-compatibility issues (and legacy code would never add the outside-edge scope in the first place, so removing it would be a no-op). However, I don’t especially like that function’s name, either, because to me it still suggests that it somehow mutates the definition context, when really all it does is manipulate the identifier’s scopes.

In any case, I’m basically fine with any of those three suggestions.

>  `internal-definition-context-add-initial-scopes` rather than `internal-definition-context-add-scopes`

I’ve been thinking more about this, and honestly, the more I wish we could just change `internal-definition-context-introduce` to manipulate both inside- and outside-edge scopes simultaneously. From a macro author’s perspective, the context is really represented by both scopes, and I can think of essentially no (non-contrived) circumstances in which one would want to explicitly add or remove one scope but not the other. Alas, it would be backwards-incompatible (though I suspect very little code would actually break in practice).

So I am backtracking on my earlier opinion: I don’t think it’s all that helpful to use the word “original” or “initial” in this function’s name. I think I mostly just don’t like how weird `internal-definition-context-add-scopes` is relative to all the other operations that manipulate scopes, all of which have the word `introduce` in their name and allow addition, removal, or flipping.

All this makes me somewhat inclined to completely give up and suggest `internal-definition-context-introduce*`. Yes, it really sucks, but does it suck any less than anything else? I don’t think so—and hey, even `syntax/parse` has `~or*`. Maybe sometimes it’s best to just admit we screwed up.

2021-08-04 15:10 UTC, michaelballantyne commented
Documentation is in and I squashed to a single commit with a descriptive message. I think this is ready to merge. @mflatt

I stuck to `internal-definition-context-add-initial-scopes`, but went with `internal-definition-context-splice-binding-identifier`. I acknowledge the imperfection of the name but still prefer it to the others. Hopefully the documentation makes the meaning clear.

2021-08-04 23:23 UTC, mflatt commented
This looks generally good to me.

My only request before you merge is about the documentation for `syntax-local-apply-transformer`. The word "hygiene" is not currently used anywhere else in the reference (to avoid having to define it). So, probably it should not be used here, and the documentation for `syntax-local-apply-transformer` should just say what it does in terms of adding and flipping scopes.

For the scribble change, just try to merge it at about the same time, and no version exception is needed on the package server (because, as you say, it's part of the main distribution). But it would be good to bump the version dependency, if that's not done already.

2021-08-09 15:32 UTC, mflatt commented
Thanks for the doc update. I've built and tested with the latest commit on my machine, but adjusted to bump the version to 8.2.0.7 (and with the Scribble commit). Should I merge that, assuming no problems discovered by the CI run that's in progress?

2021-08-09 16:07 UTC, michaelballantyne commented
@mflatt does this look better?

It doesn't look like the scribble packages specify a minimum version dependency in their info.rkt. Should I add one, or does it make sense as-is?

2021-08-09 16:11 UTC, mflatt commented
@michaelballantyne Yes — I think our messages crossed, so see above.

Adding a minimum version for `"base"` to `racket-lib` would be a good improvement for that commit.

2021-08-09 16:13 UTC, michaelballantyne commented
@mflatt oh, they did indeed cross! Feel free to merge.

2021-08-09 16:20 UTC, mflatt commented
Ok - merged!

2021-08-09 16:20 UTC, closed without merging

2021-08-09 16:22 UTC, michaelballantyne commented
Thanks! For future reference, do you bump the version number when adding new expander primitives? I wasn't clear on that vs vm primitives.

2021-08-09 16:37 UTC, mflatt commented
Yes. There are a variety of reasons to bump the version number, but one of them is that `#%kernel` has new exports, so `racket/base` needs to be recompiled to propagate them, etc.