list doc: use defproc* to separate the improper list case
racket/racket pull request #4882
Opened 2023-12-26 01:33 UTC by sorawee

Prior this PR, the improper list case is lumped into the list case (often via `or/c` or by absorbing the more specific contract into `any/c`). This results in many counterintuitive contracts. E.g., `drop` has the contract `(-> any/c natural? any/c)`, even though in most cases people use it in the way that complies `(-> list? natural? list?)`.

This PR uses `defproc*` to separate the two cases, making the contracts more precise. This style is not new: the documentation for the `append` function for example is already following the style. The PR simply applies the style more universally.

Also fixes the contract of `findf`, which actually accepts an improper list.

2023-12-26 15:38 UTC, mfelleisen commented
Thank you!

2023-12-29 12:16 UTC, mflatt requested changes
Looks good to me, with two small exceptions.

2023-12-29 12:45 UTC, sorawee commented on pkgs/racket-doc/scribblings/reference/pairs.scrbl
> +@defproc[(andmap [proc procedure?] [lst list?] ...+) any/c]{
Oof, thanks for catching that.

2023-12-30 03:00 UTC, sorawee commented
Fixed, so I will merge this if there's no further objection.

2023-12-30 10:45 UTC, merged