Update other-editors.scrbl to include langserver
racket/racket pull request #4924
Opened 2024-02-04 18:08 UTC by spdegabrielle

##### Checklist

- [ ] Bugfix
- [ ] Feature
- [ ] tests included
- [x] documentation

### Description of change
add Racket-langserver to https://docs.racket-lang.org/guide/other-editors.html

2024-02-04 18:44 UTC, spdegabrielle commented
see also https://github.com/racket/racket/pull/4925

2024-02-04 18:59 UTC, beelzebielsk commented
Two notes: I personally would not include capabilities of the language server in a discussion about setting up your editor. That's really a detail of the language server and I wouldn't want to update that every time the language server is capabilities change or grow. Second note is I don't believe bracket language server is under active development. If I remember correctly it is stalled and the maintainers have said so in an issue somewhere.

2024-02-05 00:19 UTC, spdegabrielle commented
> Two notes: I personally would not include capabilities of the language server in a discussion about setting up your editor. That's really a detail of the language server and I wouldn't want to update that every time the language server is capabilities change or grow. Second note is I don't believe bracket language server is under active development. If I remember correctly it is stalled and the maintainers have said so in an issue somewhere.

Done

2024-02-05 03:24 UTC, LiberalArtist commented on pkgs/racket-doc/scribblings/guide/other-editors.scrbl
> +implementation for Racket. This project seeks to use @hyperlink["https://github.com/racket/drracket"]{DrRacket's public APIs}
If you want a link here, I think it should be `@seclink[#:indirect? #t #:doc '(lib "scribblings/drracket-tools/drracket-tools.scrbl") "top"]{DrRacket's public APIs}`.

2024-02-05 03:25 UTC, LiberalArtist commented on pkgs/racket-doc/scribblings/guide/other-editors.scrbl
> +The @tt{racket-langserver} is a @hyperlink["http://langserver.org/"]{Language Server Protocol}
This should use `https`.

2024-02-05 03:33 UTC, LiberalArtist commented on pkgs/racket-doc/scribblings/guide/other-editors.scrbl
> +server will be automatically installed when @tt{atom-ide-racket} installs.
Since Atom was discontinued over a year ago, I'd be inclined not to mention it here.

2024-02-05 03:53 UTC, LiberalArtist requested changes
I don't think The Racket Guide should provide all of these details. Instead, I think the first step should be to contribute Scribble documentation to https://github.com/jeapostrophe/racket-langserver (which may require a decision from its maintainers about how to structure the packaging to minimize dependencies). Then, I think the guide should get something like a `@section{Other Editors via the Language Server Protocol}` that indirect-links to the new `racket-langserver` documentation.

In particular, The Racket Guide is part of the Racket release cycle, and `racket-langserver` is not. Running `raco pkg install racket-langserver` will install the latest release of the package, not the version from the date of the Racket release, so it makes sense to link to documentation matching the package actually being installed.

2024-02-05 13:25 UTC, spdegabrielle commented
> I don't think The Racket Guide should provide all of these details. Instead, I think the first step should be to contribute Scribble documentation to https://github.com/jeapostrophe/racket-langserver (which may require a decision from its maintainers about how to structure the packaging to minimize dependencies). Then, I think the guide should get something like a `@section{Other Editors via the Language Server Protocol}` that indirect-links to the new `racket-langserver` documentation.

an initial PR has been created at https://github.com/jeapostrophe/racket-langserver/pull/130

That said, I believe this is a pragmatic change that will enhance the experience for new Racket users.

2024-02-05 13:27 UTC, benknoble commented on pkgs/racket-doc/scribblings/guide/other-editors.scrbl
> +is installed. You can install an from the @hyperlink["https://download.racket-lang.org"]{official download page}
typo: `install an`

2024-02-05 13:48 UTC, mfelleisen commented
Perhaps there should be a Newbie guide that includes such details.

2024-02-05 13:54 UTC, spdegabrielle commented on pkgs/racket-doc/scribblings/guide/other-editors.scrbl
> +is installed. You can install an from the @hyperlink["https://download.racket-lang.org"]{official download page}
fixed

2024-02-05 13:59 UTC, spdegabrielle commented
> Perhaps there should be a Newbie guide that includes such details.

@mfelleisen I see 'getting started' as the newbie guide.

#4925 adds a link to the editors chapter.

2024-02-06 16:50 UTC, spdegabrielle commented
@mfelleisen is there any barrier to this PR ?
- if there is something wrong I can fix it.
-  if it is undesirable I will close it. 
 
I don't want it hanging around like a bad smell. 

I won't be creating an newbie guide today. if you like this PR can be considered an interim measure until a newbie guide is created.

2024-10-11 14:31 UTC, closed without merging