Add `case-λ`.
racket/racket pull request #4990
Opened 2024-05-09 09:04 UTC by NoahStoryM

##### Checklist

- [x] Feature
- [x] documentation

### Description of change

Add `case-λ`.

2024-05-20 17:57 UTC, mflatt requested changes

2024-05-20 17:57 UTC, mflatt commented on pkgs/racket-doc/scribblings/reference/syntax.scrbl
>  the @racket[case-lambda]-generated procedure is the same as applying a
Please add `@history[#:changed "8.13.0.5" @elem{Added @racket[case-λ].}]` before the closing curly brace for this form's documentation (and I will bump the Racket version number soon afterward).

2024-05-21 15:21 UTC, samth approved these changes

2024-05-21 19:12 UTC, merged

2024-07-09 19:09 UTC, samth commented
This change broke the algebraic package (and those that depend on it): https://plt.cs.northwestern.edu/pkg-build/server/built/fail/algebraic.txt

cc @dedbox